import {
  SiNextdotjs, SiNodedotjs, SiPostgresql, SiTypescript, SiTailwindcss,
  SiStripe, SiSendgrid, SiKotlin, SiMqtt,
  SiRaspberrypi, SiPython, SiCplusplus, SiEspressif, SiQt,
  SiAndroid, SiJetpackcompose, SiReact, SiDocker, SiGit,
  SiVercel, SiRust, SiMongodb, SiJavascript, SiFlutter,
  SiRos,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";
import type { ComponentType } from "react";

export const TECH_ICONS: Record<string, ComponentType<{ className?: string }>> = {
  // Web
  "Next.js":         SiNextdotjs,
  "Node.js":         SiNodedotjs,
  "PostgreSQL":      SiPostgresql,
  "TypeScript":      SiTypescript,
  "Tailwind":        SiTailwindcss,
  "Tailwind CSS":    SiTailwindcss,
  "Stripe":          SiStripe,
  "SendGrid":        SiSendgrid,
  "React":           SiReact,
  "JavaScript":      SiJavascript,
  "MongoDB":         SiMongodb,
  "Docker":          SiDocker,
  "Docker (basics)": SiDocker,
  "Git":             SiGit,
  "Vercel":          SiVercel,
  "Rust":            SiRust,
  "Rust (learning)": SiRust,
  // Mobile
  "Kotlin":          SiKotlin,
  "Flutter":         SiFlutter,
  "Jetpack Compose": SiJetpackcompose,
  "Android SDK":     SiAndroid,
  "MQTT":            SiMqtt,
  // Robotics / Embedded
  "Python":          SiPython,
  "C++":             SiCplusplus,
  "ESP32":           SiEspressif,
  "Qt6":             SiQt,
  "Qt6 (C++/Python)":SiQt,
  "Raspberry Pi":    SiRaspberrypi,
  "ROS2":            SiRos,
  "AWS IoT Core":    FaAws,
};

export const TECH_DESCRIPTIONS: Record<string, string> = {
  "Next.js":          "Full-stack React framework",
  "React":            "UI component library",
  "Node.js":          "Server-side JS runtime",
  "TypeScript":       "Typed JavaScript",
  "JavaScript":       "Web scripting language",
  "PostgreSQL":       "Relational database",
  "MongoDB":          "Document database",
  "Tailwind":         "Utility-first CSS",
  "Tailwind CSS":     "Utility-first CSS",
  "Stripe":           "Payment processing",
  "SendGrid":         "Transactional email",
  "Kotlin":           "Android-first language",
  "Flutter":          "Cross-platform UI SDK",
  "MVVM":             "Architecture pattern",
  "Jetpack Compose":  "Android UI toolkit",
  "Android SDK":      "Android dev platform",
  "MQTT":             "IoT messaging protocol",
  "ROS2":             "Robot operating system",
  "SLAM":             "Mapping & localization",
  "LiDAR":            "Laser-based sensing",
  "ESP32":            "Wi-Fi microcontroller",
  "Raspberry Pi":     "Single-board computer",
  "Qt6 (C++/Python)": "Desktop app framework",
  "C++":              "Systems programming",
  "Python":           "Scripting & ML language",
  "Git":              "Version control",
  "AWS IoT Core":     "Cloud IoT messaging",
  "Vercel":           "Frontend deployment",
  "Docker (basics)":  "Container platform",
  "Rust (learning)":  "Systems language",
};
